version: '3'
services:
  mysql-database:
    image: mysql:5.7
    container_name: mysql-database
    ports:
      - 3308:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=webscraper

  web-scraper:
    image: lrbarzola/laravel:7.2
    container_name: web-scraper
    ports:
      - 8080:80
    expose:
      - 80
    volumes:
      - ${PWD}:/var/www/app
    links:
      - mysql-database
    tty: true
