#!/bin/bash

# Create default .env
if [ ! -f .env ]; then
    echo "### Creating .env file ###"
    cp .env.example .env
fi

echo "### Starting containers ###"
docker-compose up -d


# Composer dependencies
echo "### Installing composer dependencies ###"
docker run --rm --interactive --tty \
    --volume $PWD:/app \
    composer install


# Application setup
echo "### Application setup ###"
./run php artisan migrate

echo "### DONE! ###"
echo ""
echo "Run ./up to start the application"