#!/bin/bash

echo "### Starting application..."
docker-compose up -d

echo "### Application running in http://localhost:8080"
echo ""

echo "### Starting worker"
./run php artisan queue:work --queue=scraper